# Generated by Django 3.2 on 2021-04-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='LinkModel',
        ),
        migrations.AlterModelOptions(
            name='linkmodel',
            options={'ordering': ['-created'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
    ]
